name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/prettier.yml@main
  test:
    name: Test
    uses: strongishllama/github-actions/.github/workflows/npm-test.yml@main
  build:
    name: Build
    uses: strongishllama/github-actions/.github/workflows/npm-build.yml@main
